### ISSUE TITLE
v2.0.0

### ISSUE THREAD

**Issue by prisae** [empymod/empymod#52]
# Development of v2 - overview and progress

These MUST be done; then create a release candidate:
  - [x] #13 Change bad names (#84)
  - [x] #14 Abstraction, sort of (#85)
  - [x] #15 Change htarg/ftarg to dicts (#81)
  - [x] #21 Replace numexpr by numba (#77, #79)
  - [x] #73 Ensure inputs are not altered (#83)
  - [x] #76 Improve EMArray (#78)
  - [x] Drop Python 3.5 support; start using f-strings ; remove backwards compatibility (#72, #80)
  - [x] Check defaults => ~change to fast ones, not most precise ones (e.g., `{'pts_per_dec': -1}`)~

With a release candidate in place, tackle these:
  - [x] Check documentation to reflect changes.
  - [x] Check docstrings and inline comments to reflect changes.
  - [x] Adjust and verify benchmarks `empymod-asv`.
  - [x] Adjust and verify examples.

**Comment by prisae** [comment]
`master` is now officially the v2.0.0 development.
